####################################
# 45.1 Вызов исключений
print(1)
raise ValueError
print(2)
####################################
####################################
# 45.2 Вызов исключений
name = "123"
raise NameError("Invalid name!")
####################################
####################################
# 45.3 Вызов исключений
try:
    num = 5 / 0
except:
    print("An error occurred")
    raise
####################################
